In [1]:
import numpy as np
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

demo_matrix[2,3]

39

In [2]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

test_array[2:3]

[12]

In [3]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [4]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [5]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

NameError: name 'pd' is not defined

In [6]:
demo_array=np.arange(0,10)

In [7]:
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
demo_array <3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [9]:
demo_array[demo_array <6]

array([0, 1, 2, 3, 4, 5])

In [10]:
np.max(demo_array)

9

In [11]:
import pd as pandas

ModuleNotFoundError: No module named 'pd'

In [18]:
import pandas as pd

In [19]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}



In [20]:
dataframe = pd.DataFrame(data)



In [21]:


grouped_data = dataframe.groupby('prodID')

grouped_data.max()

,prodname,profit
prodID,,
101,X,2738
102,Y,2727
103,Z,3497
104,X,7347


In [22]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [23]:
s1 = pd.Series(['a', 'b'])

s2 = pd.Series(['c', 'd'])

In [24]:
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [25]:
pd.concat(s1, s2)


TypeError: first argument must be an iterable of pandas objects, you passed an object of type "Series"

In [26]:
pd.concat[s1, s2]


TypeError: 'function' object is not subscriptable

In [27]:
 demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

In [28]:
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [29]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])



In [30]:
flowers['daisy']

5

In [31]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

In [32]:
test_array[2:3]

[12]

In [33]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

In [34]:
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [1]:
simple_list=[1,2,3]


In [3]:
import numpy as np
np.array(simple_list)


array([1, 2, 3])

In [4]:
array_lists=[[12,2,3],[3,4,5],[4,5,7]]
np.array(array_lists)

array([[12,  2,  3],
       [ 3,  4,  5],
       [ 4,  5,  7]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(10,3)

array([[1.50493026e-04, 7.80901039e-01, 5.33409917e-01],
       [7.61581839e-01, 1.63444484e-01, 2.82641212e-01],
       [7.29367629e-01, 6.15507629e-01, 7.64682766e-01],
       [1.30678031e-01, 6.84605966e-01, 5.96236894e-01],
       [8.04394376e-01, 3.50358932e-02, 9.85360112e-01],
       [8.79134727e-02, 8.77713907e-01, 8.44197420e-02],
       [6.46354402e-01, 2.39642919e-01, 6.21272458e-01],
       [1.80984355e-01, 9.09027849e-01, 5.75032026e-01],
       [5.84925918e-01, 5.53003245e-01, 5.08723560e-01],
       [2.49469981e-01, 4.95713281e-01, 2.10860576e-01]])

In [13]:
np.random.randint(12,20,5)

array([12, 14, 19, 16, 18])

In [15]:
a= np.eye(3)

In [16]:
a.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
sampl= np.arange(12,21)

In [18]:
sampl[2]

14

In [21]:
sampl[2,3]

IndexError: too many indices for array

In [23]:
sampl

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
sampl[3,6]

IndexError: too many indices for array